<a href="https://colab.research.google.com/github/selsaady1/MAT-421-Elsaady/blob/main/Module_D_(Elsaady).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## Module D, Linear Equations and Regression
## Saif Elsaady
## MAT 421, Febuary 12 2023

In [ ]:
## 1.1 Introduction

In many different disciplines, linear algebra is a branch of mathematics that is extensively used. In data science as well as machine learning, linear algebra is crucial. Numerous data science as well as machine learning methodologies can be better understood with a firm grasp of linear algebraic concepts.

Sets - A set is a collection of objects {}

Union - A U B - A set including all elements of A and B

Intersect - A n B - A set including all elements that belong to A & B

Naturals - N = {1,2,3,4,..}

Wholes - W = N U {0}

Integers - Z = W U {-1,-2,-3,...}

Rationals - Q = { p/g : p ∊ Z , q ∊ Z \ {0}}

Irrationals - I = A set of real numbers that are not expressible as fractions of integers

Reals - R = Q U I

Complex Numbers - C = {a + bi: a, b ∊ R, i = sqrt(-1) }

A vector is a point in a particular area, or a tuple (RN as n tuple). A column vector is written vertically, while a row vector is written horizontally. The vector in Rn with all zeros is known as the zero vector. A vector's length can be determined by looking at its norm. Every component of the added vectors is added pairwise to form the vector addition. The product of the relevant elements in each vector is added to form the dot product of two vectors. Any object in a group is said to be linearly independent if it cannot be expressed as a linear combination of all the other things in the set.

In the example below we write a vector as a linear combination of another vector.

Given the row vectors v=[0,0,2], w=[4,-1,0], and u=[0,2,0], write the vector x=[-4,3,2] as a linear combination of v, w, and u.

In [ ]:
import numpy as np
from numpy import arccos, dot
v = np.array([[0,0,2]])
w = np.array([[4,-1,0]])
u = np.array([[0,2,0]])
x = 1*v-1*w+1*u
print(x)

[[-4  3  2]]


A rectangular table of integers with m rows and n columns is called a "m-n matrix." The Python dot method in Numpy is used to generate the product of two matrices P and Q. A matrix is transposed when its rows and columns are reversed. A square matrix is a nn matrix, meaning that its rows and columns are equal in number. An essential characteristic of square matrices is the determinant. A square matrix with ones on the diagonal as well as zeros everywhere else is the identity matrix.

In the example below we find the determinant of a matrix and verify it.

Use Python to find the determinant of the matrix M=[[2,2,5,3],[3,2,4,1],[1,0,0,3],[0,4,3,2]]


In [ ]:
from numpy.linalg import det

M = np.array([[2,2,5,3],
              [3,2,4,1],
              [1,0,0,3],
              [0,4,3,2]])
print('M:\n', M)

print('Determinant: %.1f'%det(M))
I = np.eye(4)
print('I:\n', I)
print('M*I:\n', np.dot(M, I))

M:
 [[2 2 5 3]
 [3 2 4 1]
 [1 0 0 3]
 [0 4 3 2]]
Determinant: -86.0
I:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
M*I:
 [[2. 2. 5. 3.]
 [3. 2. 4. 1.]
 [1. 0. 0. 3.]
 [0. 4. 3. 2.]]


In [ ]:
## 1.2 Elements of Linear Algebra

A new vector is created from a subset in linear algebra by multiplying each vector by a factor and then adding the results. The outcome of linear combination is a linear subspace. A subset U V that is closed under scalar as well as vector multiplication is known as the linear subspace (of V).

An example of solving for the corss product is shown below:

Find the cross product of (1 2 3) x (5 3 2):

=image.png

In [ ]:
import numpy as np
x = np.array([[1, 2, 3]])
z = np.array([[5, 3, 2]])
print(np.cross(x, z)) #cross product throught python and we confirm we get the same answer.

[[-5 13 -7]]


Column Space: Assume that A(nxm) is a nxm matrix with the following columns: a1,..., am. The length of A's columns is known as its column space, indicated by the symbol col(A).

A list of column vectors u1,..., um is said to be linearly independent when none of them can be expressed as linear combinations of one another.

Let U be a linear subspace of V in the dimension theorem. There are always the identical number of elements in any foundation of U. The length & number of elements are the same for all bases of U. (U).

If all of the u's are pairwise orthogonal and have a norm of 1, then a list of vectors u1,..., um is said to be orthonormal.

Let U V be a linear subspace having orthonormal basis q1,..., qm. This is known as an orthogonal projection. When v V is projected onto U, the orthogonal projection is Pu v = sum(j=1) v, qj > qj.

Suppose U V be a linear subspace with orthonormal basis q1,..., qm, and let v V. This represents the best approximation theorem. ||v-Pu v|| = ||v-u|| for any u > U.

Let u1 v V be orthogonal according to the Pythagorean Theorem. It is evident that ||u||2 + ||v||2 equals ||u + v||2.

Cauchy-Schwarz: Including all u1 v V, |u,v>| = |u|| |v||

Let a1,...,am in Rn be linearly independent (Gram-Schmidt). Then, an orthonormal basis, q1,...,qm of span, exists (a1,...,am).

Let A R(dxd) be a square matrix to discuss eigenvalues and eigenvectors. If x!= 0 is a non-zero vector such that Ax = x, then R is an eigenvalue of A. An eigenvector is vector x.

In this example python programming is used to find the Eigenvector and eigenvalue.



In [ ]:
import numpy as np
from numpy.linalg import eig
x = np.array([ [3, 3, 5], [4, 6, 5] , [5, 6, 2]])
w,v = eig(x)
print('E-value:', w)
print('E-vector', v)

E-value: [13.164414  0.835586 -3.      ]
E-vector [[-0.47813671 -0.76138656 -0.57062689]
 [-0.66629777  0.64571311 -0.19020896]
 [-0.57221724 -0.05783672  0.79887765]]


In [ ]:
## 1.3 Linear Regression

Given its simplicity,, linear regression is commonly applied in real-world settings. The models are simpler to fit than those whose unknown parameters are connected to them non-linearly since they depend linearly on them.QTQ = I is a restatement of the statement that Q has orthonormal columns. Q in particular has a left inverse, which is QT. Whatever m and n are, the equation R = QTA is valid. Whether or not the matrix is square is unimportant.

In [ ]:
# The following code below computes the QR decomposition. 
import numpy as np
from numpy.linalg import qr
x = np.array([[3, 2], [3, 1]])

Q,R = qr(x)
print('Q:', Q)
print('R:', R)

z = np.dot(Q, R)
print('QR:', z)

Q: [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
R: [[-4.24264069 -2.12132034]
 [ 0.         -0.70710678]]
QR: [[3. 2.]
 [3. 1.]]


Normal Equations - Assume that b is a vector and that A is a nxm matrix with linearly independent columns. The normal equations, AT Ax = AT b, are satisfied by the solution here to the least-squares problem min||Ax-b||.

A = QR is a QR decomposition of A where Q is a R(nxm) matrix with QT Q = I(mxm) and T is an upper triangle. Let A R(nxm) be a nxm matrix with a linearly independent column, allow b Rn be a vector, and then let b Rn be the vector in the least squares using QR method.